### ISSUE TITLE
getConnectedAccountTransaction has '0x0' for value, fee, gas used and gas price

### ISSUE THREAD

**Issue by ipatka** [netgum/archanova#10]
When fetching a specific account creation transaction the value, fee and gas object are all 0x0

https://kovan.etherscan.io/tx/0xee99ff45fadc0c35f9f7c30ef9d6e3942d6ec529ca54b174fb0b111d425ec023

![Screen Shot 2019-05-27 at 7 55 03 PM](https://user-images.githubusercontent.com/4401444/58442460-7ca4f000-80b9-11e9-8c36-346bafeed733.png)

**Comment by stanislaw-glogowski** [comment]
Those fields are filled after transaction changes status to `Completed`. You can track transaction status in `sdk.event$`
