### ISSUE TITLE
Account creation refunds more than the gas cost

### ISSUE THREAD

**Issue by ipatka** [netgum/archanova#11]
This is probably documented somewhere else but I was wondering why the account creator gets paid slightly more than the gas fees of the TX.

For example
https://kovan.etherscan.io/tx/0xee99ff45fadc0c35f9f7c30ef9d6e3942d6ec529ca54b174fb0b111d425ec023

gas cost: 0.00191435147774
Eth transferred: 0.00219528361

How is the fee calculated?

**Comment by stanislaw-glogowski** [comment]
@ipatka - we still working on proper gas calculation

**Comment by stanislaw-glogowski** [comment]
Gas fees in current version:
* account deployment - fixed `650000 gas`
* account proxy transactions -  sum of:
  - execution fee: `(120000 + (n-1) x 25000)`, 
     where `n` is a number of batch transaction `(1-5)`
  - estimated gas for each of batch transaction
* account friend recovery - fixed `250000 gas`
