### ISSUE TITLE
Unable to run sendAccountTransaction or createAccountPayment

### ISSUE THREAD

**Issue by ipatka** [netgum/archanova#12]
I attempted to use `sendAccountTransaction` and `createAccountPayment` but `Run` is disabled. Is this because I have a 0 ETH virtual account balance? How do I obtain a virtual account balance? Is this related to the payment channel?

![Screen Shot 2019-05-27 at 8 34 53 PM](https://user-images.githubusercontent.com/4401444/58443307-35216280-80bf-11e9-8fc5-59bc1f98f0b8.png)

**Comment by stanislaw-glogowski** [comment]
It looks like there was a problem with indexer. Please create new account, then deploy and you will be able to `sendAccountTransaction`
Use `top-up account virtual balance` to obtain a virtual account balance.

**Comment by ipatka** [comment]
![Screen Shot 2019-05-30 at 11 31 58 AM](https://user-images.githubusercontent.com/4401444/58644092-8f444280-82ce-11e9-9b6e-c699245d0750.png)

Confirmed it's working now
