### ISSUE TITLE
Unable to play tictactoe

### ISSUE THREAD

**Issue by ipatka** [netgum/archanova#13]
I see a reference to tic-tac-toe in the app section. What does this refer to?
![Screen Shot 2019-05-27 at 8 39 02 PM](https://user-images.githubusercontent.com/4401444/58443386-9d704400-80bf-11e9-8a53-46a2bf8c3cbc.png)

**Comment by stanislaw-glogowski** [comment]
`Tic-Tac-Toe` example app added in #16:

[![IMAGE ALT TEXT](http://img.youtube.com/vi/dy2qv7a9-FY/0.jpg)](http://www.youtube.com/watch?v=dy2qv7a9-FY "Archanova Tic-Tac-Toe Example")

**Comment by ipatka** [comment]
Confirmed this is working for me also
