### ISSUE TITLE
Unable to use createRequestAddAccountDeviceUrl

### ISSUE THREAD

**Issue by ipatka** [netgum/archanova#14]
What should the `createRequestAddAccountDeviceUrl` feature do? I am running 2 instances with deployed wallets on 5100 and 5200 but the `run` is disabled.

![Screen Shot 2019-05-27 at 8 42 15 PM](https://user-images.githubusercontent.com/4401444/58443466-0bb50680-80c0-11e9-9773-17a2e23cd425.png)
![Screen Shot 2019-05-27 at 8 41 51 PM](https://user-images.githubusercontent.com/4401444/58443467-0bb50680-80c0-11e9-968e-7238c783535c.png)

**Comment by stanislaw-glogowski** [comment]
To `createRequestAddAccountDeviceUrl` your account needs to be disconnected.
