### ISSUE TITLE
[ethjs-abi] invalid hex string

### ISSUE THREAD

**Issue by jsidorenko** [netgum/archanova#17]
When I tried to call the `estimateWithdrawAccountPayment(hash)` method, I got an error:
`{reason: "[ethjs-abi] invalid hex string, hex must be prefixed and alphanumeric (e.g. 0x023..)", value: null}`

Steps to reproduce:
1) sdk.createAccountPayment(null, ethToWei(0.01)) => the transaction with status Reserved will be created
2) sdk.grabAccountPayment(hash, receiver) => for receiver I've put a address of non-smart account. The status of the tx will be Created
3) sdk.estimateWithdrawAccountPayment(hash) => you'll get the error above

**Comment by stanislaw-glogowski** [comment]
Can you check `hash` attribute value. It looks like it is `null`

**Comment by jsidorenko** [comment]
here is the request that is being sent: https://ropsten.archanova.run/account/0x7C48b3328Bd1F40F9e58bEE55169c0AC35bf1691/payment/0xd6f139caee2b41eb62d049ff8d3a804258de9ec15d8b5d5c5fa7d2ce76352145

Probably, it's a playground related issue

**Comment by stanislaw-glogowski** [comment]
@jsidorenko try to use `0xd6f139caee2b41eb62d049ff8d3a804258de9ec15d8b5d5c5fa7d2ce76352145` as `hash` in `sdk. estimateWithdrawAccountPayment`

**Comment by jsidorenko** [comment]
![image](https://user-images.githubusercontent.com/5252494/58736739-3c1ddd00-83ff-11e9-9c81-69f8521162de.png)
Here is the result
