### ISSUE TITLE
Can't process the transaction to non smart wallet

### ISSUE THREAD

**Issue by jsidorenko** [netgum/archanova#18]
Steps to reproduce:
1) sdk.createAccountPayment(receiver, value) -> as a receiver set the non smart wallet account
=> transaction status will be Completed
2) in order to process it call the sdk.estimateWithdrawAccountPayment(hash)
3) sdk.submitAccountTransaction(estimated) => the result is 500 error without any explanation what went wrong

**Comment by stanislaw-glogowski** [comment]
#6 we still working on error handling, please check `estimated` object and required account balance (real)

**Comment by jsidorenko** [comment]
Account balance (real): 0.102256 ETH
I think it should be enough
