### ISSUE TITLE
Wrong estimateWithdrawFromAccountVirtualBalance() behaviour

### ISSUE THREAD

**Issue by jsidorenko** [netgum/archanova#19]
When I call the `sdk.estimateWithdrawFromAccountVirtualBalance()` it should just return me the estimated object, but instead, it additionally creates a Withdrawal transaction

**Comment by jsidorenko** [comment]
P. S. I got this behaviour in the playground

**Comment by stanislaw-glogowski** [comment]
Payments are protected by guardian and sender signature both signatures have impact on transaction cost. To protect double spending, virtual balance is updated after estimation.
We probably improve that flow on future releases
