### ISSUE TITLE
npm run start:sdk:playground:5100 fails

### ISSUE THREAD

**Issue by dekanbro** [netgum/archanova#21]
Run:
$ npm i @archanova/cli -g
$ npm i @archanova/sdk -S
$ npm run bootstrap
$ npm run compile

$ npm run start:sdk:playground:5100

Error:
> archanova@0.0.0 start:sdk:playground:5100 /home/dekan/github/playground/archanova
> cross-env PORT=5100 lerna run --stream --scope "@archanova/sdk-playground" start

lerna notice cli v3.13.4
lerna info filter [ '@archanova/sdk-playground' ]
lerna info Executing command in 1 package: "npm run start"
@archanova/sdk-playground: > @archanova/sdk-playground@1.0.0 start /home/dekan/github/playground/archanova/packages/sdk-playground
@archanova/sdk-playground: > react-scripts start
@archanova/sdk-playground: There might be a problem with the project dependency tree.
@archanova/sdk-playground: It is likely not a bug in Create React App, but something you need to fix locally.
@archanova/sdk-playground: The react-scripts package provided by Create React App requires a dependency:
@archanova/sdk-playground:   "webpack": "4.29.6"
@archanova/sdk-playground: Don't try to install it manually: your package manager does it automatically.
@archanova/sdk-playground: However, a different version of webpack was detected higher up in the tree:
@archanova/sdk-playground:   /archanova/node_modules/webpack (version: 3.12.0)
...

Workaround:
disable preflight check by addding this to sdk-playground/.env allows it to proceed
SKIP_PREFLIGHT_CHECK=true

**Comment by stanislaw-glogowski** [comment]
Fixed
