### ISSUE TITLE
Account device should be in Deployed state

### ISSUE THREAD

**Issue by yogeshgo05** [netgum/archanova#22]
This error is thrown after the account Deployment is done and before execute transaction. 

The error thrown by the call to `estimateAccountTransaction` and we have work around currently by commenting the code that is throwing that error. Not sure why we have that error thrown. Because device is connected and account is connected.

**Comment by stanislaw-glogowski** [comment]
Please update sdk version to latest one - we completely rebuilded our testnet envs on Friday.
