### ISSUE TITLE
submitAccountTransaction - is returning a 500 Internal server this morning.

### ISSUE THREAD

**Issue by yogeshgo05** [netgum/archanova#23]
Following are the details of the account 
accountAddress :  "0x1f4C808b10082F4ab6638b1b774621C0819e0553" (Already Deployed)
ensName: "y12-1.archanova.kovan"

This was working well last night but just started giving me error as we started

**Comment by yogeshgo05** [comment]
More Info Different account 
https://kovan.etherscan.io/address/0x5363556dca1a7dd64d92b8f46def7553b494c5bd

There is enough ETH for accountTransaction to succceed 

ExecuteTransaciton worked once
and it fails during second attempt to call executeTransaction (sdks submitAccountTransaction)

**Comment by stanislaw-glogowski** [comment]
Please update sdk version to latest one - we completely rebuilded our testnet envs on Friday.

**Comment by yogeshgo05** [comment]
We updated to 12. I started getting this error on Saturday

**Comment by yogeshgo05** [comment]
The problem persists still though.  This is the sdk version we are using ^1.0.0-alpha.12

**Comment by stanislaw-glogowski** [comment]
@yogeshgo05 - I tested sending transaction flow and I can not reproduce error.
Can you create and deploy fresh account?
Bug can be connected with moving env to new server (I deployed new contract instances)
