### ISSUE TITLE
When Account Contract does not have enough gas

### ISSUE THREAD

**Issue by yogeshgo05** [netgum/archanova#29]
Sdk backend server returns internal server error instead of returning appropriate error. 

Precisely we are using sdk.accountDeploy() returns `internal server error`

**Comment by stanislaw-glogowski** [comment]
What sdk version are you using? 
Did you try to deploy account using playground?
https://github.com/netgum/archanova#sdk-playground

**Comment by yogeshgo05** [comment]
^1.0.0-alpha.12 , thats SDK version we are using.

**Comment by stanislaw-glogowski** [comment]
#34
