### ISSUE TITLE
Account Contract has enough gas but submitAccountTransaction fails on calling second time.

### ISSUE THREAD

**Issue by yogeshgo05** [netgum/archanova#30]
Account Contract has enough gas but submitAccountTransaction fails on calling second time.
Execute transaction works the first time but fails with an internal server error for the second time.

    `   const accountObject = await sdkInit.estimateAccountTransaction(
      contractAddress.bettingContractAddress,
      '0',
      this.state.contractInstance.methods
        .requestWithdrawal(
          web3.utils.toWei(withdrawAmount, 'ether'),
          withdrawalAddress,
        )
        .encodeABI(),
    );

    console.log('Account Object =>', accountObject);

    // Execute Transaction
    let executeTransaction = await sdkInit.submitAccountTransaction(
      accountObject,
    );`

**Comment by stanislaw-glogowski** [comment]
@yogeshgo05 - `submitAccountTransaction fails on calling second time.` 
Do you want to submit estimated transaction multiple times?

**Comment by yogeshgo05** [comment]
Thanks for the response.

Actually when user withdraws from yolos UI we do submitAccounttransaction but we do estimate transaction before submit.

I thought each submitAccountTransaction is independent of previous ones so shouldn’t we estimate every time before we do submitAccounttransaction.

**Comment by stanislaw-glogowski** [comment]
There should be estimation before each `submitAccountTransaction`. Account `nonce` is a part of `accountObject` (it increase on every account transaction)

**Comment by yogeshgo05** [comment]
We have an estimation before each submitAccountTransaction. Nonce is not the issue. As its still failing to execute the second transaction even on incremented nonce in the accountObject.  We're still having this issue.
