### ISSUE TITLE
@archanova/sdk:  Middleware reference docs result in error

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#37]
## Description 

When following [the redux middleware guide](https://github.com/netgum/archanova/blob/develop/docs/sdk/redux_integration.md), the code will throw an `undefined` error.

When running from Typescript, `const sdk;` will throw an error stating const variables must be initialized.

**Comment by stanislaw-glogowski** [comment]
Readme fixed :)
```typescript
import { createReduxSdkMiddleware, ISdkReduxState } from '@archanova/sdk';
import { applyMiddleware, createStore } from 'redux';
import reducers from './reducers';

const sdk; // ... sdk object
const store = createStore<ISdkReduxState>(
  reducers,
  {},
  applyMiddleware(
    createReduxSdkMiddleware(sdk),
  ),
);
```
