### ISSUE TITLE
Account status remains as created after account deployment

### ISSUE THREAD

**Issue by FSM1** [netgum/archanova#41]
account state does not change to 'Deployed' after the deployment of the account occurs. 

Please see the logs below: 
![image](https://user-images.githubusercontent.com/12774278/61493131-26ff0c80-a9b3-11e9-9d17-68012a8be079.png)

the correct state is loaded the next time the SDK is initialized.

**Comment by stanislaw-glogowski** [comment]
For nodejs env you need to set api WebSocket constructor

```javascript
const { createSdk, getSdkEnvironment } = require('@archanova/sdk');
const Ws = require('ws');

let sdkEnv = getSdkEnvironment('main');

sdkEnv = sdkEnv.setConfig('apiWebSocketConstructor', Ws); // <---

const sdk = createSdk(sdkEnv);
```

**Comment by FSM1** [comment]
thanks @stanislaw-glogowski that worked a charm.
