### ISSUE TITLE
playground stops working when clicking "auto accept sdk actions"

### ISSUE THREAD

**Issue by lyricalpolymath** [netgum/archanova#46]
if you disable the "auto accept sdk actions" checkbox
and if you re-enable it later
some functions seem to not work properly

in the following screenshot
![Screenshot 2019-07-23 at 21 06 30](https://user-images.githubusercontent.com/516744/61740434-ede9e200-ad8e-11e9-9bea-0f992b14c594.jpg)

also empty if you try to widthdraw
![Screenshot 2019-07-23 at 21 07 08](https://user-images.githubusercontent.com/516744/61740300-9e0b1b00-ad8e-11e9-9b89-1eee8cfd238c.jpg)

I think the problem appeared when I tried disabling and re-enabling the "auto accept sdk actions"

**Comment by stanislaw-glogowski** [comment]
Widthdraw bug fixed. The problem was not connected with `auto accept sdk actions`
