### ISSUE TITLE
deposit payment not returning hash

### ISSUE THREAD

**Issue by Perseverance** [netgum/archanova#48]
I've ran into a hash that cannot be deposited through the sdk. I am using ropsten, but cant figure out what the problem is. I've deposited many more but this specific one does not go through: `0x0288dff5fbecc8dd82c472824c1d6763778e4aa99163ce2c4bd6b107bcd104e9`

Some access to the relayer logs would be wonderful :)

**Comment by stanislaw-glogowski** [comment]
Hi, it look like there was some problems with our infura ropsten node. I'll check why reconnect  was not working properly.

**Comment by stanislaw-glogowski** [comment]
I can not reproduce issue. Please reopen issue if you detect similar problems.
