### ISSUE TITLE
Invalid recovery extension state | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#53]
## Description
A deployed account had an attempt at deploying an account recovery extension. However it cant be queried, the setup account recovery function is forbidden, attempts to deploy the extension result in a null transaction hash. 

### To inspect
*  Open up playground
*  Initialise on Sokol using this PVT: 0xbf121c12d4be119eec1da5d3abf2bbaa6f28c1068ac0067d563dd9516191ec62
*  Connect account
*  Open Account Recovery section

**Comment by stanislaw-glogowski** [comment]
It's because `0xbf121c12d4be119eec1da5d3abf2bbaa6f28c1068ac0067d563dd9516191ec62` device has `Created` state inside of `Deployed`
Try to setup recovery from `0x9caE9a0e3358415c7aC5FfC0770E112A6a323D25` device.
