### ISSUE TITLE
Device state not updating post deploy | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#55]
## Description of scenario

*  Client device initialises & creates account
*  Client adds guardian as device
*  Guardian device connects to client account
*  Guardian funds & deploys account
*  Guardian adds social recovery to client account
*  Guardian set up as social recovery
*  Client connects to account
*  Client removes guardian as device 

## Issue
When trying to estimate & submit a transaction from the newly created account, the SDK throws a, account is in created state, error, when using getConnectedAccountDevices, the client device entry's state is "Created" where as all the other entries are deployed.

**Comment by stanislaw-glogowski** [comment]
That's correct. Guardian also needs to deploy client device:
https://playground.archanova.run/#deploy_account_device
