### ISSUE TITLE
Next State on failed hanging deployment locking account | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#56]
## Description
When a deploy account transaction is submitted by the relayer with 0Gwei set as the gas price  (#52 ) the next state is locked at "Deployed" preventing the sdk from attempting to submit a new transaction. 

## Possible solutions
*  A means of canceling transactions 
*  Next state can be reset by some means

**Comment by stanislaw-glogowski** [comment]
Gas price / pending transactions related issues was fixed.

**Comment by RyRy79261** [comment]
@stanislaw-glogowski This error has not been resolved.

I have recreated in the playground on sokol for using the device private key 0x480438f9e266355fbca0e07270e1e0608e61dae28def0fde736b2c25e29531d1
