### ISSUE TITLE
Can't detect other tokens

### ISSUE THREAD

**Issue by pedrouid** [netgum/archanova#58]
I used the `getTokens` and `getToken` method on the playground and I couldn't find the token I transferred to the active account.

accountAddress: 0x2AC21C80e9bA7f8FB21e18086D439ccdc9DE823A
tokenAddress: 0x3615757011112560521536258c1E7325Ae3b48AE

However I could top up the virtual balance using the token contract address so this issue wasn't too critical. So when I query the accountVirtualBalances, I get the following response:

<img width="503" alt="Screenshot 2019-08-12 17 26 16" src="https://user-images.githubusercontent.com/10136079/62880873-512fba00-bd26-11e9-8af6-071839b159bd.png">

The token contract address gets listed on the virtual balances but it doesnt identify the name and symbol.

**Comment by stanislaw-glogowski** [comment]
1. To get real (on-chain) balance of a token please use:
https://playground.archanova.run/#get_token_balance
2. `getTokens` and `getToken` methods are used to get informations about tokens which was added to virtual balance.
3. `symbol` and `name` will be filled for tokens which implements `ERC20Detailed` from https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Detailed.sol

**Comment by stanislaw-glogowski** [comment]
is this that token?
https://rinkeby.etherscan.io/address/0x3615757011112560521536258c1E7325Ae3b48AE#code

**Comment by stanislaw-glogowski** [comment]
Issue was found. Name / symbol detection should works for future virtual balance operations.
