### ISSUE TITLE
Virtual balance not updating when depositing through proxy

### ISSUE THREAD

**Issue by morelazers** [netgum/archanova#59]
Rinkeby env with 1.1.0.

Account contract: `0x863d89960C447EBCD7f37EB725A15C17433F7DCF`
Proxy contract: https://rinkeby.etherscan.io/address/0x117547f447780df51c6835c1d4d4ddd18b47e5d0#code

Virtual balance manager displays this on Etherscan, but SDK virtual balance stays at 0.
![image](https://user-images.githubusercontent.com/2966123/62910856-89d2a080-bdc5-11e9-9542-73ed0e7f823c.png)

**Comment by stanislaw-glogowski** [comment]
We had some problems with our infura node.
I just tested whole flow and it works:
https://rinkeby.etherscan.io/tx/0x22fd8d7cf1f05f2d5da9b28f55f5a5bd94e72b69809621a899e3f8312a43cd2d
https://rinkeby.archanova.run/account/0x863d89960C447EBCD7f37EB725A15C17433F7DCF
