### ISSUE TITLE
500 error when there is not enough to cover account deployment

### ISSUE THREAD

**Issue by jsidorenko** [netgum/archanova#6]
If I have not enough funds to deploy the account, I'll get a 500 error from the server

**Comment by ipatka** [comment]
I also saw this. Adding Kovan Eth from this faucet to the Account Address worked for me
https://faucets.blockxlabs.com/ethereum

**Comment by stanislaw-glogowski** [comment]
@jsidorenko It's correct - `500` in that situation means that there was a `internal error` (revert on eth transaction) Please estimate account deployment before calling deploy.

**Comment by jsidorenko** [comment]
Shouldn't we return an error message back in those cases? 500 error usually means that you did something wrong and the server went down. `internal error` - server components wise.

**Comment by stanislaw-glogowski** [comment]
@jsidorenko - You right, we will try to improve error handling in future release

**Comment by stanislaw-glogowski** [comment]
#34
