### ISSUE TITLE
Relayer returning estimates with 0 Gwei | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#60]
## Description

2 previous issues, (#56, #52) we closed despite the errors not being addressed. 

The relayer will go through phases of sending back estimates that were calculated with a gas price of 0 repeatedly, I have recreated both issues in version 1.0.0 & 1.1.0 on the playground.

**Comment by RyRy79261** [comment]
The pseudocode for the repair is as follows: 

```
if(networkId == 77 || networkId == 100){
   estimate.gasPrice = anyToBN(1000000000);
}
```

@stanislaw-glogowski Please apply this to the function that generates estimates in the relayer

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 Thanks for fix
