### ISSUE TITLE
Revert Error:  Social recovery submission  | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#61]
## Description

After collecting a signature for a social recovery with the settings of 1 Required Friend, with 1 Friend account set up.

Submitting of social recovery returns an error of revert. 

Possibly linked to the 0 Gwei gas issues (#60  #52 #56 ) as `submitAccountFriendRecovery` returns a hash and theres an issue with creating estimations to execute

**Comment by stanislaw-glogowski** [comment]
https://github.com/netgum/archanova/issues/62#issuecomment-520919798
