### ISSUE TITLE
Friend not found: Collect account friend signature | Sokol & Rinkeby

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#62]
## Description
After starting a social recovery, the friend signature function returns an `Error: Not Found` on submission of the signature 

![image](https://user-images.githubusercontent.com/10461622/62939742-3fa3ec00-bdd2-11e9-847c-403c65cc3b87.png)

**Comment by RyRy79261** [comment]
I have recreated the issue on Rinkeby

![image](https://user-images.githubusercontent.com/10461622/62941801-35382100-bdd7-11e9-827a-ba6435d70e81.png)

**Comment by RyRy79261** [comment]
@stanislaw-glogowski Please advise as I am following the sequence of functions specified by the gitbook docs.

**Comment by stanislaw-glogowski** [comment]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/h59-h0I8TKQ/0.jpg)](http://www.youtube.com/watch?v=h59-h0I8TKQ "Archanova Friend Recovery")

**Comment by RyRy79261** [comment]
@stanislaw-glogowski  I'm not sure what this low quality video is meant to solve but I am no closer to having my issue resolved.

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 video is still processing ... It demonstrate whole process

**Comment by stanislaw-glogowski** [comment]
Please reload youtube video and change quality to 4k

**Comment by RyRy79261** [comment]
@stanislaw-glogowski From what I see here I followed everything exactly as indicated when I logged the issue.

**Comment by RyRy79261** [comment]
@stanislaw-glogowski Confirming it works my side, thanks! :D
