### ISSUE TITLE
Virtual balance not always correctly updated when depositing through proxy

### ISSUE THREAD

**Issue by morelazers** [netgum/archanova#63]
Rinkeby env, 1.1.0.

This is what Etherscan displays:
![image](https://user-images.githubusercontent.com/2966123/62983808-1f2c6e00-be74-11e9-8d04-f2e73cccb0c0.png)

But my balance in `sdk.state.account.balance.virtual` is `0.01`, I expect it to be `0.02`.

Proxy contract: https://rinkeby.etherscan.io/address/0x030dd09b84d60db9bb624379331f1be2f05fb1f9

Account contract: https://rinkeby.etherscan.io/address/0x359280c417d6c782db1da040ac46fdd27ecaa8ba

**Comment by stanislaw-glogowski** [comment]
@morelazers thanks for feedback. I'll try to fix it Today (it looks like we have another problem with our eth node)

**Comment by stanislaw-glogowski** [comment]
Fixed
