### ISSUE TITLE
400 Error: SDK reset leads to relayer api errors 

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#65]
## Description
After resetting the SDK, attempts to submit queries to the relayer return 400 errors.

In the example image, I was submitting a friend recovery request, the estimation works however

![image](https://user-images.githubusercontent.com/10461622/63016684-9b36ae00-be94-11e9-83b1-4ec06881d070.png)

**Comment by RyRy79261** [comment]
![image](https://user-images.githubusercontent.com/10461622/63016989-5b23fb00-be95-11e9-980f-bc52ee75c0d2.png)

**Comment by RyRy79261** [comment]
![image](https://user-images.githubusercontent.com/10461622/63017015-6aa34400-be95-11e9-88cc-1d552a3e35ae.png)

**Comment by RyRy79261** [comment]
The error still persists @jamesyoung

**Comment by RyRy79261** [comment]
![image](https://user-images.githubusercontent.com/10461622/63438784-34356e00-c42d-11e9-916d-b3f83ed8ce51.png)

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 Can you console.log `sdk.state.accountFriendRecovery` ... it would help us a lot.

**Comment by RyRy79261** [comment]
@stanislaw-glogowski 

I logged in, then I logged out which triggers the sdk reset, these are the results:
![image](https://user-images.githubusercontent.com/10461622/63448700-c72ad400-c43e-11e9-9d67-7b1eb3430448.png)


It seems I cant replicated the error now though

**Comment by RyRy79261** [comment]
@stanislaw-glogowski it only works when I have the console logs between the steps for some reason

**Comment by RyRy79261** [comment]
This is the state when I receive the error: 
![image](https://user-images.githubusercontent.com/10461622/63449049-926b4c80-c43f-11e9-9bcc-aaf801da58b3.png)

**Comment by RyRy79261** [comment]
So it sets the state to have the account request then reverts it to null
![image](https://user-images.githubusercontent.com/10461622/63449170-dbbb9c00-c43f-11e9-8790-85c4ad84ea46.png)

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 can you check full recovery flow - I can not reproduce error. Previous one was probably connected with backend update (changing guardian signature signer)

**Comment by stanislaw-glogowski** [comment]
`+` before submit please console.log `sdk.state.accountFriendRecovery` object

**Comment by RyRy79261** [comment]
![image](https://user-images.githubusercontent.com/10461622/63449576-a95e6e80-c440-11e9-9401-819a88bfaf82.png)

**Comment by RyRy79261** [comment]
This is the function calling it 
![image](https://user-images.githubusercontent.com/10461622/63449601-b8ddb780-c440-11e9-906f-0c0bc47c5ee4.png)
