### ISSUE TITLE
Payable function error | Function requiring eth revert

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#67]
## Description 

A function which takes accepts eth in exchange for tokens, which returns any remaining eth sent, only reverts when the transaction is sent via Abridged & not remix or any ganache tests.

Network Sokol

**Comment by RyRy79261** [comment]
Same transaction sent by Remix

https://blockscout.com/poa/sokol/tx/0xd946c273c4cfbd1db29982938cb00bd4fc01b8b903fef327a4f085a116aa04b5/token_transfers

**Comment by RyRy79261** [comment]
I'm able to send the transaction through if I increase the required sending value by 0.000001, this is not required when sending in remix.

**Comment by RyRy79261** [comment]
The issue runs the risk of scaling as the volumes increase so arbitrarily increasing the values is not a solve.

**Comment by RyRy79261** [comment]
Theres a possibility that the relayer is subtracting the gas from the value being sent which would explain the need to add more eth than the value would typically require.

@stanislaw-glogowski would this assumption be correct?

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 Relayer gets refund from account real balance no transaction value.
