### ISSUE TITLE
Relayer cant find social recovery extension despite deployment | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#70]
## Description

On the 6th recovery of an account, the relayer throws a `Not Found` error when attempting to start the recovery, but when attempting to add recovery, the console reads `Error: extension already added`
![image](https://user-images.githubusercontent.com/10461622/63100321-1ff9f880-bf77-11e9-8923-cb9993fff82f.png)

**Comment by RyRy79261** [comment]
@stanislaw-glogowski 

Am I missing something?

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 it seems that you added extension device but didn't setup it.

**Comment by RyRy79261** [comment]
@stanislaw-glogowski I did set it up as I've been using the same account for 3 days

**Comment by RyRy79261** [comment]
@stanislaw-glogowski as I said in the ticket, I've recovered the account 6 times

**Comment by RyRy79261** [comment]
Heres another account as example thats been used for the last few days, currently getting errors from the relayer when executing start recovery

**Comment by RyRy79261** [comment]
![image](https://user-images.githubusercontent.com/10461622/63102586-b0d2d300-bf7b-11e9-81bb-a87d4e49069f.png)

**Comment by RyRy79261** [comment]
https://blockscout.com/poa/sokol/address/0x019eac7d840eabf71265020b59bdf1b1f776189a/transactions

**Comment by RyRy79261** [comment]
@stanislaw-glogowski I tried recreating the issue again and didn't receive the same error.

I'll close the ticket later if it doesn't crop up today

**Comment by RyRy79261** [comment]
#77 Indicates this has not been resolved
