### ISSUE TITLE
No means of signature verification without the signer providing their device address

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#73]
## Description 

While the SDK allows the signing & verifying of a signed message, the issue is that the address that does the signing is different to the address that interacts with the chain.

This means that in order to validate that a signature came from an admin for example, the account verifying the signature needs to know if the resulting signer is a device of the account which provided the signature.

There is no means of looking up an external accounts devices.

**Comment by RyRy79261** [comment]
@jamesyoung @stanislaw-glogowski

**Comment by RyRy79261** [comment]
This is the flow I'm seeking: 
Verify Signature -> Signer -> Get target Account devices -> check is signer is a device of the target account

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 I added `sdk.recoverAccountDeviceFromPersonalMessageSignature` in lates version of sdk:
https://playground.archanova.run/#recover_account_device_from_personal_message_signature

The flow should works that way:
* account `A` device signs message
* account `A` sends signature to account `B`
* account `B` recovers account `A` device and verifies device properties (state, type etc.)

**Comment by RyRy79261** [comment]
Epic, Thanks @stanislaw-glogowski !
