### ISSUE TITLE
Type Error - Null is not of type TAnyData - EstimateAccountTransaction 

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#74]
## Description

When trying to estimate a eth transfer, specifying in the data field a `null`, typescript says that `null` is not a valid type of `TAnyData`

![image](https://user-images.githubusercontent.com/10461622/63265464-f817d700-c28d-11e9-8441-1532a94ae29a.png)

**Comment by stanislaw-glogowski** [comment]
with `strictNullChecks` please use `Buffer.alloc(0)` instead of `null`
