### ISSUE TITLE
Error typo

### ISSUE THREAD

**Issue by pedrouid** [netgum/archanova#75]
When calling `getToken` with a contractAddress that doesn't match a listed token on `getTokens`, the backend returns an error `Error: token nod found`

**Comment by pedrouid** [comment]
The issue could be related because it's a recently deployed token that perhaps hasn't indexed by the backend

Contract address: `0xa4c42CA2296E62156b8e935DB46637FFCaBCd21D`

**Comment by stanislaw-glogowski** [comment]
`getToken` and `getTokens` methods returns only tokens which was used with virtual payments.

The flow should look like this:
1. Send token to account
2. Top-up account virtual balance with token
3. `getToken` details
