### ISSUE TITLE
Playground not functional on Sokol 

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#80]
## Description 

When attempting to initialise the playground, it hangs waiting for 3min requests that return nothing and keeps retrying

![image](https://user-images.githubusercontent.com/10461622/64006597-f3b3af80-cb12-11e9-886a-af88bced2fa2.png)

**Comment by RyRy79261** [comment]
@stanislaw-glogowski 
@jamesyoung

**Comment by RyRy79261** [comment]
This is in the console on load:
![image](https://user-images.githubusercontent.com/10461622/64006744-31183d00-cb13-11e9-85e5-66a732d0678c.png)

**Comment by stanislaw-glogowski** [comment]
@RyRy79261 can you check if the issue is still present?

**Comment by RyRy79261** [comment]
@stanislaw-glogowski The issue appears resolved, my instances are also able to connect now
